### ISSUE TITLE
"Unable to decode m-play-info"

### ISSUE THREAD

**Issue by abartov** [jakshin/mixcaster#1]
Hello.

Thank you for offering this tool!  I tried it on https://www.mixcloud.com/others/ but got:

jakshin.mixcaster.ApplicationException: Unable to decode m-play-info from https://www.mixcloud.com/others/

**Comment by jakshin** [comment]
Sorry, I had kind of forgotten about this project for a while there, but I recently wanted to start using it again, so I've dusted it off and fixed it up. I've tested it with the `others` Mixcloud user specifically, and it's working.

**Comment by abartov** [comment]
Thank you very much; it works great! :)
