### ISSUE TITLE
Failed to parse http response (com.apollographql.apollo.exception.ApolloParseException)

### ISSUE THREAD

**Issue by Slicelord** [jakshin/mixcaster#4]
Hi Jakshin,

Mixcaster looks amazing, but I am having trouble. When I try to generate a feed, I get

500 Internal Server Error
Failed to parse http response (com.apollographql.apollo.exception.ApolloParseException) 

I'm using Ubuntu 20.04 and Java 17

Is it because mixcloud has changed its code?

All the best

Slicelord

**Comment by jakshin** [comment]
I finally found time to look into this -- sorry for the long delay. Yeah, Mixcloud made a change that broke things, but it was an easy fix and the new release v1.1.1 works again. Cheers!
